"""empty message

Revision ID: 19606b08990b
Revises: 
Create Date: 2022-11-01 16:27:39.772659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19606b08990b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_to_id', sa.Integer(), nullable=True),
    sa.Column('notification_message', sa.String(length=200), nullable=True),
    sa.Column('notification_type', sa.String(length=200), nullable=True),
    sa.Column('notification_status', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
