"""empty message

Revision ID: 201b312c6030
Revises: 1e2d9cbe05f2
Create Date: 2022-12-18 14:38:37.790083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201b312c6030'
down_revision = '1e2d9cbe05f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
