"""empty message

Revision ID: 3d003389cf95
Revises: d4790bb62892
Create Date: 2022-12-02 10:44:35.737621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d003389cf95'
down_revision = 'd4790bb62892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product', table_name='product')
    op.create_index('ix_products', 'product', [sa.text('name ASC'), sa.text('barcode ASC'), sa.text('id ASC')], unique=True)
    op.create_index('ix_purchases', 'purchase', [sa.text('id ASC'), sa.text('seller_name ASC'), sa.text('seller_invoice_number ASC'), sa.text('total_amount ASC'), sa.text('subtotal_amount ASC'), sa.text('date_created ASC')], unique=False)
    op.create_index('ix_sales', 'sale', [sa.text('id ASC'), sa.text('total_amount ASC'), sa.text('subtotal_amount ASC'), sa.text('date_created ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales', table_name='sale')
    op.drop_index('ix_purchases', table_name='purchase')
    op.drop_index('ix_products', table_name='product')
    op.create_index('ix_product', 'product', ['name', 'barcode', 'id'], unique=False)
    # ### end Alembic commands ###
