"""empty message

Revision ID: 409858000cd7
Revises: 7b96fc32229a
Create Date: 2022-11-22 13:06:14.312454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409858000cd7'
down_revision = '7b96fc32229a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'eight_tax_amount')
    op.drop_column('purchase', 'eighteen_tax_amount')
    op.add_column('purchase_tax', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('purchase_tax', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_tax', 'date_modified')
    op.drop_column('purchase_tax', 'date_created')
    op.add_column('purchase', sa.Column('eighteen_tax_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('purchase', sa.Column('eight_tax_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
