"""empty message

Revision ID: 460fed5c81ef
Revises: 9fd4fee45821
Create Date: 2023-01-16 21:11:42.313777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460fed5c81ef'
down_revision = '9fd4fee45821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('purchased_price_wo_tax', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('purchase_item', sa.Column('product_purchased_price_wo_tax', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_item', 'product_purchased_price_wo_tax')
    op.drop_column('product', 'purchased_price_wo_tax')
    # ### end Alembic commands ###
