"""empty message

Revision ID: 4ead3890b841
Revises: 409858000cd7
Create Date: 2022-12-01 16:40:39.260101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ead3890b841'
down_revision = '409858000cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products', table_name='product')
    op.drop_index('idx_products_barcode', table_name='product')
    op.drop_index('idx_products_id', table_name='product')
    op.drop_index('idx_products_name', table_name='product')
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.create_index('idx_products_name', 'product', ['name'], unique=False)
    op.create_index('idx_products_id', 'product', ['id'], unique=False)
    op.create_index('idx_products_barcode', 'product', ['barcode'], unique=False)
    op.create_index('idx_products', 'product', ['id', 'barcode', 'name', 'stock', 'tax', 'purchased_price', 'selling_price', 'expiration_date', 'date_created', 'date_modified'], unique=False)
    # ### end Alembic commands ###
