"""empty message

Revision ID: 6731d18532b3
Revises: 460fed5c81ef
Create Date: 2023-01-17 20:20:10.469356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6731d18532b3'
down_revision = '460fed5c81ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('measure', sa.Enum('pcs', 'kg', 'liter'), nullable=True, default="pcs"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'measure')
    # ### end Alembic commands ###
