"""Total without tax SaleTax

Revision ID: 67c4a23e477f
Revises: e936efc6c1fe
Create Date: 2024-08-20 16:08:00.038093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c4a23e477f'
down_revision = 'e936efc6c1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_tax', sa.Column('total_without_tax', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_tax', 'total_without_tax')
    # ### end Alembic commands ###
