"""empty message

Revision ID: 71bad18d95cf
Revises: 6731d18532b3
Create Date: 2023-01-17 20:29:34.033976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bad18d95cf'
down_revision = '6731d18532b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('product_measure', sa.Enum('pcs', 'kg', 'liter'), nullable=True))
    op.add_column('sale_item', sa.Column('product_measure', sa.Enum('pcs', 'kg', 'liter'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_item', 'product_measure')
    op.drop_column('purchase_item', 'product_measure')
    # ### end Alembic commands ###
