"""empty message

Revision ID: 753a22831fb6
Revises: 88c20d46d399
Create Date: 2023-04-20 16:06:22.047624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753a22831fb6'
down_revision = '88c20d46d399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('rabat', sa.Numeric(precision=3, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_item', 'rabat')
    # ### end Alembic commands ###
