"""empty message

Revision ID: 775c7d8e7d52
Revises: 3f816961134b
Create Date: 2023-01-23 21:45:05.661783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775c7d8e7d52'
down_revision = '3f816961134b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchase_type', sa.Enum('purchase', 'investment', 'expense'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'purchase_type')
    # ### end Alembic commands ###
