"""empty message

Revision ID: 7b96fc32229a
Revises: e1fec53f9d1b
Create Date: 2022-11-08 15:58:16.374807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b96fc32229a'
down_revision = 'e1fec53f9d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('staff', 'manager', 'owner', 'superadmin'), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
