"""empty message

Revision ID: 88c20d46d399
Revises: 775c7d8e7d52
Create Date: 2023-01-23 22:28:47.306341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c20d46d399'
down_revision = '775c7d8e7d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_tax', sa.Column('total_without_tax', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_tax', 'total_without_tax')
    # ### end Alembic commands ###
