"""empty message

Revision ID: 95b6a4fe2444
Revises: 753a22831fb6
Create Date: 2023-04-21 00:24:05.313767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b6a4fe2444'
down_revision = '753a22831fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('rabat_amount', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'rabat_amount')
    # ### end Alembic commands ###
