"""empty message

Revision ID: 9fd4fee45821
Revises: c90b2e91e445
Create Date: 2023-01-16 13:25:54.010544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd4fee45821'
down_revision = 'c90b2e91e445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_item', 'price_without_tax')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('price_without_tax', sa.NUMERIC(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
