"""empty message

Revision ID: c90b2e91e445
Revises: 201b312c6030
Create Date: 2022-12-23 22:07:27.409291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90b2e91e445'
down_revision = '201b312c6030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('gross_profit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sale', sa.Column('net_profit_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'net_profit_amount')
    op.drop_column('sale', 'gross_profit_amount')
    # ### end Alembic commands ###
