"""empty message

Revision ID: e1fec53f9d1b
Revises: ffb335cd8dd4
Create Date: 2022-11-03 10:12:52.605552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fec53f9d1b'
down_revision = 'ffb335cd8dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_star', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'notification_star')
    # ### end Alembic commands ###
