"""empty message

Revision ID: e8ad79f56336
Revises: 4ead3890b841
Create Date: 2022-12-01 16:42:39.512172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ad79f56336'
down_revision = '4ead3890b841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_id', table_name='product')
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    # ### end Alembic commands ###
