"""Added product expiration date to purchase item

Revision ID: e936efc6c1fe
Revises: 
Create Date: 2024-01-09 16:02:18.763918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e936efc6c1fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_item', sa.Column('product_expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_item', 'product_expiration_date')
    # ### end Alembic commands ###
