"""empty message

Revision ID: ffb335cd8dd4
Revises: 19606b08990b
Create Date: 2022-11-01 21:54:01.275016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb335cd8dd4'
down_revision = '19606b08990b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_read', sa.Boolean(), nullable=True))
    op.drop_column('notification', 'notification_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_status', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('notification', 'notification_read')
    # ### end Alembic commands ###
